definitions:
  dto.BodyCreateRider:
    properties:
      capacity:
        $ref: '#/definitions/dto.CreateDimensions'
      id:
        type: string
      serviceArea:
        type: integer
      status:
        type: integer
    type: object
  dto.BodyLocation:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  dto.CreateDimensions:
    properties:
      depth:
        type: integer
      height:
        type: integer
      width:
        type: integer
    type: object
  dto.RiderResponse:
    properties:
      capacity:
        $ref: '#/definitions/dto.riderResponseCapacity'
      id:
        type: string
      location:
        $ref: '#/definitions/dto.riderResponseLocation'
      serviceArea:
        $ref: '#/definitions/dto.riderResponseArea'
      status:
        type: integer
      user:
        $ref: '#/definitions/dto.riderResponseUser'
    type: object
  dto.riderResponseArea:
    properties:
      id:
        type: integer
      identifier:
        type: string
    type: object
  dto.riderResponseCapacity:
    properties:
      depth:
        type: integer
      height:
        type: integer
      width:
        type: integer
    type: object
  dto.riderResponseLocation:
    properties:
      latitude:
        type: number
      longitude:
        type: number
    type: object
  dto.riderResponseUser:
    properties:
      id:
        type: string
      lastName:
        type: string
      name:
        type: string
    type: object
  dto.ridersResponse:
    properties:
      id:
        type: string
      name:
        type: string
      serviceArea:
        type: integer
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/riders:
    get:
      consumes:
      - application/json
      description: gets all riders in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ridersResponse'
            type: array
      summary: get all riders
    post:
      consumes:
      - application/json
      description: creates a new rider
      parameters:
      - description: Add rider
        in: body
        name: rider
        required: true
        schema:
          $ref: '#/definitions/dto.BodyCreateRider'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RiderResponse'
      summary: create rider
  /api/riders/{id}:
    get:
      description: gets a rider from the system by its ID
      parameters:
      - description: Rider id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RiderResponse'
      summary: get rider
    put:
      consumes:
      - application/json
      description: updates a rider's information
      parameters:
      - description: Update rider
        in: body
        name: rider
        required: true
        schema:
          $ref: '#/definitions/dto.BodyCreateRider'
      - description: Rider id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RiderResponse'
      summary: update rider
  /api/riders/{id}/location:
    put:
      consumes:
      - application/json
      description: updates a rider's location
      parameters:
      - description: Update rider
        in: body
        name: rider
        required: true
        schema:
          $ref: '#/definitions/dto.BodyLocation'
      - description: Rider id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.RiderResponse'
      summary: update rider location
swagger: "2.0"
